# Generated by Django 4.2.6 on 2024-07-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bd_raw_data_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=120, verbose_name='nombreCompleto')),
                ('edad_nominal', models.IntegerField(verbose_name='edadActual')),
            ],
            options={
                'verbose_name_plural': 'RegnuevosDatoPersonas',
                'db_table': 'RegnuevosDatosPersona',
            },
        ),
        migrations.CreateModel(
            name='bd_raw_data_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombrePersona')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellidoPersona')),
                ('edad', models.DateField(verbose_name='Fecha_Nacimiento')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'RegDatosPersona',
            },
        ),
    ]
